name = "thegearsh-com"
compatibility_date = "2025-10-03"

[[d1_databases]]
binding = "DB"
database_name = "gearsh_db"
database_id = "625dcd0a-84b7-4cce-a8b4-af6e4d3b37b0"

[[r2_buckets]]
binding = "GEARSH_BUCKET"
bucket_name = "gearsh-assets"
