// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7zcl3NVymNUIH-3P7_zt2c_QrAxBjYCo',
    appId: '1:345771972520:web:bf69a6f1ee24604c10ef9d',
    messagingSenderId: '345771972520',
    projectId: 'gearsh-app',
    authDomain: 'gearsh-app.firebaseapp.com',
    storageBucket: 'gearsh-app.firebasestorage.app',
    measurementId: 'G-P6GD580TZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMoPObE7kTYDjRxRilImsz8oHLZgTXSbg',
    appId: '1:345771972520:android:10c8c049127738e410ef9d',
    messagingSenderId: '345771972520',
    projectId: 'gearsh-app',
    storageBucket: 'gearsh-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiA1xeC_sLhUTykQfOl6WnpfIg0VJN0B0',
    appId: '1:345771972520:ios:44c82b3ee37765ca10ef9d',
    messagingSenderId: '345771972520',
    projectId: 'gearsh-app',
    storageBucket: 'gearsh-app.firebasestorage.app',
    iosClientId: '345771972520-r2bm7qkapaaon85gf59feoe2dcp7imec.apps.googleusercontent.com',
    iosBundleId: 'com.gearsh.app.gearshApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiA1xeC_sLhUTykQfOl6WnpfIg0VJN0B0',
    appId: '1:345771972520:ios:6baeb59d62f321e310ef9d',
    messagingSenderId: '345771972520',
    projectId: 'gearsh-app',
    storageBucket: 'gearsh-app.firebasestorage.app',
    iosClientId: '345771972520-nqdrn951o2tju8lt2i2dd61apr3bm0ef.apps.googleusercontent.com',
    iosBundleId: 'com.thegearsh.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7zcl3NVymNUIH-3P7_zt2c_QrAxBjYCo',
    appId: '1:345771972520:web:34224bf1b14e715610ef9d',
    messagingSenderId: '345771972520',
    projectId: 'gearsh-app',
    authDomain: 'gearsh-app.firebaseapp.com',
    storageBucket: 'gearsh-app.firebasestorage.app',
    measurementId: 'G-KJNT1SNGRK',
  );
}
